"""SQLite storage for news bodies and LLM verdicts.

Two tables in a single DB at ``data/processed/news.sqlite``:

  news_articles
    Cached body text for fetched SEC filings (8-K, 10-Q, etc).
    Keyed by (symbol, source_id) where source_id is the SEC accession.
    Body is stored as cleaned plain text (BeautifulSoup `get_text(' ')`),
    truncated to MAX_BODY_CHARS so LLM context budgets are predictable.

  predictions_news_verdict
    One verdict per (universe, symbol, as_of). Generated by the daily
    pipeline against the model's top-N long picks. Audit-only — paper
    backtest does NOT read this table yet.

We keep this DB separate from `predictions_log` and `paper.sqlite` so:
  - news ingestion can't block the prediction or backtest path
  - LLM-related schema changes don't trip the predict-DB migrations
"""

from __future__ import annotations

import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from packages.common.config import settings

# Body cap — Gemma 4 can handle ~8k tokens of context comfortably, and
# 8-K bodies are often 5-30k characters. We keep the first 8000 chars
# (most relevant: the lead summary and item disclosures come first).
MAX_BODY_CHARS = 8000

_NEWS_DDL = """
CREATE TABLE IF NOT EXISTS news_articles (
    symbol         TEXT NOT NULL,
    source         TEXT NOT NULL,  -- 'edgar'
    source_id      TEXT NOT NULL,  -- SEC accession number
    form_type      TEXT,           -- '8-K', '10-Q', etc.
    items          TEXT,           -- comma-separated 8-K item codes
    filing_date    DATE NOT NULL,
    url            TEXT,
    title          TEXT,
    body           TEXT,           -- cleaned text, truncated to MAX_BODY_CHARS
    body_chars     INTEGER,        -- length of original (untruncated) body
    fetched_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, source, source_id)
);
CREATE INDEX IF NOT EXISTS news_symbol_date
    ON news_articles (symbol, filing_date);

CREATE TABLE IF NOT EXISTS predictions_news_verdict (
    universe          TEXT NOT NULL,
    symbol            TEXT NOT NULL,
    as_of             DATE NOT NULL,
    verdict           TEXT NOT NULL,   -- 'PANIC' | 'RESET' | 'UNCLEAR'
    confidence        REAL NOT NULL,   -- 0-1
    key_factors_json  TEXT,            -- JSON array of strings
    evidence_sources_json TEXT,        -- JSON array
    model_name        TEXT NOT NULL,   -- e.g. 'gemma4:latest'
    n_sources         INTEGER,         -- how many SEC filings fed the prompt
    trail_5d          REAL,            -- snapshotted at classify time
    trail_20d         REAL,
    predicted_return  REAL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (universe, symbol, as_of)
);
CREATE INDEX IF NOT EXISTS verdict_universe_date
    ON predictions_news_verdict (universe, as_of);
"""


def _news_db_path() -> str:
    return str(Path(settings.predictions_sqlite_path).parent / "news.sqlite")


def init_news_db(path: str | None = None) -> str:
    """Create the news schema. Idempotent.

    Enables WAL journal mode so the pipeline's outer verdict-writer
    connection and the inner news_articles-writer connection inside
    `fetch_filings_for_symbol` don't deadlock on the same file.
    WAL allows N concurrent readers + 1 writer without exclusive locks
    blocking each other for the duration of a transaction.
    """
    p = path or _news_db_path()
    Path(p).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(p)
    try:
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA busy_timeout = 5000")  # ms
        conn.executescript(_NEWS_DDL)
        conn.commit()
    finally:
        conn.close()
    return p


@contextmanager
def news_conn(path: str | None = None) -> Iterator[sqlite3.Connection]:
    """Context-managed news DB connection. Cross-thread safe (FastAPI).

    Sets busy_timeout so writes briefly block (up to 5s) instead of
    immediately erroring when another connection is mid-write.
    """
    p = init_news_db(path)
    conn = sqlite3.connect(p, check_same_thread=False)
    conn.execute("PRAGMA busy_timeout = 5000")
    try:
        yield conn
    finally:
        conn.close()
