"""Drop garbage OHLCV bars and ghost index_membership rows.

Post-incident cleanup. The wf_sp500_canon backtest reproduced +307% in 2014
because NCC (delisted in 2008, ticker reassigned to a low-volume penny stock)
showed up in index_membership with garbage yfinance OHLCV that oscillated
between $0.50 and $3.83 daily — perfect false mean-reversion signal.

Filters applied (idempotent):
  1. Drop OHLCV bars where the close-to-close move > 50% in either direction.
     Real S&P 500 / NIFTY100 stocks don't move 50% in a day except in extreme
     events (flash crash, halt, going-concern news). 677 bars in NCC's history
     matched — every one was garbage.
  2. Drop OHLCV bars with volume < 5000 (NYSE) or < 1000 (NSE). Real index
     members have liquid trading. 1200-share-volume bars are stale/reassigned
     ticker data.
  3. Drop OHLCV bars with close < $1.00 (NYSE) or < Rs.10 (NSE). Real index
     names don't trade as penny stocks; sub-$1 prices indicate a delisted /
     reassigned ticker.
  4. Drop index_membership rows for known reassigned tickers (NCC, PCLN, FB).
     PCLN renamed to BKNG in 2018; FB renamed to META in 2022. Both still
     show stale `end_date=fallback` rows — the strategy can pick BKNG/META
     directly so we don't lose anything.

Outputs: prints before/after row counts. DOES NOT touch training parquets
(those are regenerated by build_dataset.py after this).
"""

from __future__ import annotations

import duckdb


def clean_ohlcv() -> dict:
    """Delete suspect OHLCV bars in-place. Returns deletion counts."""
    c = duckdb.connect("data/processed/market.duckdb")
    counts: dict = {}

    counts["before_total"] = c.execute("SELECT COUNT(*) FROM ohlcv_daily").fetchone()[0]

    # 1. Big-move bars. Using a window over (symbol, exchange) → catches the
    #    NCC-style oscillation perfectly.
    n_big = c.execute("""
        WITH ret AS (
            SELECT symbol, exchange, bar_date, source, close,
                   LAG(close) OVER (PARTITION BY symbol, exchange ORDER BY bar_date) AS prev_close
            FROM ohlcv_daily
        ),
        bad AS (
            SELECT symbol, exchange, bar_date, source
            FROM ret
            WHERE prev_close IS NOT NULL AND prev_close > 0
              AND (close / prev_close > 1.5 OR close / prev_close < 0.67)
        )
        DELETE FROM ohlcv_daily o
        USING bad
        WHERE o.symbol = bad.symbol
          AND o.exchange = bad.exchange
          AND o.bar_date = bad.bar_date
          AND o.source = bad.source
    """).fetchone()
    counts["bars_with_big_moves"] = n_big[0] if n_big else 0

    # 2. Low-volume bars (different thresholds per exchange).
    n_lowv = c.execute("""
        DELETE FROM ohlcv_daily
        WHERE (exchange = 'NYSE' AND volume < 5000)
           OR (exchange = 'NSE' AND volume < 1000)
    """).fetchone()
    counts["low_volume_bars"] = n_lowv[0] if n_lowv else 0

    # 3. Sub-$1 / sub-Rs.10 bars.
    n_cheap = c.execute("""
        DELETE FROM ohlcv_daily
        WHERE (exchange = 'NYSE' AND close < 1.0)
           OR (exchange = 'NSE' AND close < 10.0)
    """).fetchone()
    counts["penny_bars"] = n_cheap[0] if n_cheap else 0

    counts["after_total"] = c.execute("SELECT COUNT(*) FROM ohlcv_daily").fetchone()[0]
    c.close()
    return counts


def drop_ghost_membership() -> dict:
    """Delete index_membership rows for known reassigned tickers and for any
    symbol that has zero remaining OHLCV bars after the cleanup."""
    c = duckdb.connect("data/processed/market.duckdb")
    counts: dict = {}
    counts["before_total"] = c.execute("SELECT COUNT(*) FROM index_membership").fetchone()[0]

    # Hardcoded reassigned tickers — yfinance returns garbage data for these.
    KNOWN_REASSIGNED = ["NCC", "PCLN", "FB"]
    n_known = c.execute(f"""
        DELETE FROM index_membership
        WHERE symbol IN ({','.join('?' for _ in KNOWN_REASSIGNED)})
    """, KNOWN_REASSIGNED).fetchone()
    counts["known_reassigned"] = n_known[0] if n_known else 0

    # Any membership row where the symbol+exchange has NO OHLCV bars at all.
    n_orphan = c.execute("""
        DELETE FROM index_membership
        WHERE NOT EXISTS (
            SELECT 1 FROM ohlcv_daily o
            WHERE o.symbol = index_membership.symbol
              AND o.exchange = index_membership.exchange
        )
    """).fetchone()
    counts["orphan_no_ohlcv"] = n_orphan[0] if n_orphan else 0

    counts["after_total"] = c.execute("SELECT COUNT(*) FROM index_membership").fetchone()[0]
    c.close()
    return counts


def main() -> None:
    print("=" * 70)
    print("OHLCV cleanup")
    print("=" * 70)
    ohlcv = clean_ohlcv()
    print(f"  before: {ohlcv['before_total']:>10,} rows")
    print(f"  -big moves (>50%):   {ohlcv['bars_with_big_moves']:>10,}")
    print(f"  -low volume:         {ohlcv['low_volume_bars']:>10,}")
    print(f"  -sub-$1 / sub-Rs.10:   {ohlcv['penny_bars']:>10,}")
    print(f"  after:  {ohlcv['after_total']:>10,} rows")

    print()
    print("=" * 70)
    print("Membership cleanup")
    print("=" * 70)
    mem = drop_ghost_membership()
    print(f"  before: {mem['before_total']:>5,} rows")
    print(f"  -known reassigned (NCC, PCLN, FB): {mem['known_reassigned']:>5,}")
    print(f"  -orphan (no OHLCV):                {mem['orphan_no_ohlcv']:>5,}")
    print(f"  after:  {mem['after_total']:>5,} rows")


if __name__ == "__main__":
    main()
